### ISSUE TITLE
New Rule: component-display-name

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint-react#1]
Require `public static displayName` property on classes that extend `React.Component`.

Since we don't have the type checker yet, this will only be able to verify classes that directly extend `React.Component`, not any subclasses of it.

**Comment by JKillian** [comment]
I think React can infer a reasonable displayName in many cases, we should be sure this is really worth it before implementing

**Comment by adidahiya** [comment]
It infers it from the variable identifier, which gets minified in production. I'd find this useful

**Comment by estaub** [comment]
I just got through debugging a React resolve()-related bug that only showed up in production mode, where code is minified and it's really hard to know where you are.  As @adidahiya noted, inferred displayNames are mostly junk in this context.  In production code, real displayNames are valuable signposts in a semantic desert.

**Comment by OzairP** [comment]
@estaub Sounds like you should have used source maps? IIRC dev tools will resolve source maps right to the component itself.

**Comment by adidahiya** [comment]
Should be covered by typescript-eslint + https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md
