### ISSUE TITLE
jsx-alignment could be split into multiple rules

### ISSUE THREAD

**Issue by radix** [palantir/tslint-react#100]
jsx-alignment has multiple behaviors:

- in a multiline tag, the props must start on a separate line from the tag
- in a multiline tag, each prop must be on its own line
- in a multiline tag, the `>` must be on its own line

(there may be more that I'm missing)

It might be nice to make separate rules for these checks.

**Comment by kenjiru** [comment]
That's a great idea, as I'm not a big fan of the last rule, with `>` being on it's own line..

**Comment by nksfrank** [comment]
I'd like to see this, too. I like to have the closing `>` on the same line as the last prop

**Comment by olee** [comment]
Anyone intending to write up a PR to this one?
I would really like to split tags in multiple lines, but still allow multiple tags in the same line.

**Comment by adidahiya** [comment]
Closing due to #210
