### ISSUE TITLE
New rule: jsx-equals-spacing

### ISSUE THREAD

**Issue by bolatovumar** [palantir/tslint-react#103]
Would be nice to have this rule:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-equals-spacing.md

I'm willing to implement it and make a PR.

**Comment by JonWallsten** [comment]
@bolatovumar  Would you mind adding "jsx-tag-spacing" while you're at it? ;)

**Comment by bolatovumar** [comment]
I gotta get this one sorted out first. I might look into other rules after,
for sure
