### ISSUE TITLE
New rule: jsx-indent

### ISSUE THREAD

**Issue by mDibyo** [palantir/tslint-react#112]
Would be nice to implement: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md

I am willing to give it a go.

**Comment by adidahiya** [comment]
I think the core TSLint `indent` rule should handle this since TypeScript parses JSX syntax anyway.

**Comment by mDibyo** [comment]
@adidahiya `indent` does not seem to be catching errors. This is probably related to palantir/tslint/#2814.

**Comment by mattnedrich** [comment]
Has this been fixed?

**Comment by adidahiya** [comment]
closing in favor of https://github.com/palantir/tslint/issues/2814

**Comment by shubich** [comment]
> Has this been fixed?

My solution for this issue - https://gist.github.com/shubich/ee8ff287037783981e6511531d001163
