### ISSUE TITLE
New rule: jsx-no-trailing-semicolon

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint-react#116]
We had a case in our code where a semicolon was accidentally used at the end of a line of a tsx statement. Since this is almost always unintended, it makes sense to have a lint rule to warn against it. The rule would warn against code like the following:

```
<div>
  <SomeComponent/>;
</div>
```

(haven't thought about the rule name that much, so take the title with a grain of salt)

**Comment by tomauty** [comment]
I was just looking for something like this. Maybe `no-errant-characters`? Is there an actual use-case for having characters not wrapped in an element in a JSX statement? For RN there is not.

**Comment by adidahiya** [comment]
Closing due to deprecation timeline #210, let's focus on getting support in eslint
