### ISSUE TITLE
react/prefer-stateless-function for tslint-react

### ISSUE THREAD

**Issue by dreadwail** [palantir/tslint-react#117]
Hello. When using ESlint with React I always enable the following rule:

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md

I was not able to find the same kind of rule for tslint-react. 

1. Is this something you feel would fit well into the project?
2. If so, can I submit a pull-request to add the feature?

Thanks

**Comment by tomalexhughes** [comment]
Surprised to see that there's been no further discussion on this after 8 months.

I miss this a lot from ESLint and would love to see this for TypeScript.

**Comment by WillSquire** [comment]
Is this on the roadmap? With hooks and memo it seems to be a useful rule

**Comment by VincentLanglet** [comment]
+1

**Comment by gangwarily** [comment]
The omission of this rule was one of the first thing I noticed between ``tslint-config-airbnb`` and ``eslint-config-airbnb``. I'm still using eslint for the time being and applying it to my TypeScript file with ``typescript-eslint-parser``.

**Comment by isaachinman** [comment]
@adidahiya What's the status on this? Is this free to pick up? Any advice on where to start?

**Comment by adidahiya** [comment]
This is still open to PRs but it sounds like a tricky rule to implement correctly and keep in mind that it will be easy to use the ESLint version of this rule within the next few months (https://github.com/palantir/tslint/issues/4534).

**Comment by isaachinman** [comment]
Yeah, saw those updates recently. Will leave this in favour of ESLint.

**Comment by adidahiya** [comment]
Closing due to deprecation timeline #210
