### ISSUE TITLE
jsx-use-translation-function: Option to ignore punctuation

### ISSUE THREAD

**Issue by whatisaphone** [palantir/tslint-react#119]
It would be nice if there were a way to make this rule ignore non-alphabetical characters (unicode category letter), for cases like these:

```
function CloseButton() {
  return <div class="close">×</div>;
}
```

The character `×` is U+00D7: MULTIPLICATION SIGN

```
function Foo({ label, t }) {
  return <li>{t('label')}: {label}</li>;
}
```

**Comment by adidahiya** [comment]
This should be fixed in v3.5.0+
