### ISSUE TITLE
New rule: jsx-space-before-trailing-slash

### ISSUE THREAD

**Issue by balthild** [palantir/tslint-react#125]
Prefer `<MyComponent />` than `<MyComponent/>`

[XHTML species](https://www.w3.org/TR/xhtml1/#C_2):

> ## C.2. Empty Elements
>
> Include a space before the trailing `/` and `>` of empty elements, e.g. `<br />`, `<hr />` and `<img src="karen.jpg" alt="Karen" />`. Also, use the minimized tag syntax for empty elements, e.g. `<br />`, as the alternative syntax `<br></br>` allowed by XML gives uncertain results in many existing user agents.

**Comment by j13z** [comment]
It would be nice to have the option to either enforce the _presence_ or _absence_ of whitespace before the closing `/>` (whatever your team can agree on).

I'd be happy to add this the to the #144 pull request, if you need help, @no23reason (you'd have to generalize the rule to something like `jsx-self-closing-consistent-whitespace` and add an option to the rule, as well as some new tests).

**Comment by no23reason** [comment]
@j13z Thank you for the comment, however I don't really see the point of purposefully *omitting* the space. I know it is not needed I just don't know anyone would use the space eliminating version. [The W3C recommends the space](https://www.w3.org/TR/xhtml1/#C_2), Prettier [will add it in](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACKEYEsxwYwAWhAtrgM6W5QDmGlADgIYGUa0YsA2PRpTmQYwWdSgB0okKJRgYAHhgC8GABQBKFQD4MAHlzDGEAK4AnAsokgAZhAgA6AFZM611Nqky5GAJ4r1LWVdAyNKUws4K1t7Z1drbh4YaIBlCDJCADc4M38eaBE4BXkYCAw7SIFCHlpCUowAIzM4FgBrd09paB8ALwDNHX1DBnDzS2s7Rxc3EETk6zSMjDhsqAx8+hzGiAATfwgbIiKSsoqCKvXaojKmlva0bRAAGhAIJjxu5FAWMzMIAHcAAo-BCUZAgFiZCC4HbPCFyZA2XiUOAvJpsVpwGApVhgWh0ZAwMwmVEgHYQMCI5Gk2goswwQFmMRkFhUngol5OSgKABCTLAmOxLAyABlamyOa8TDAmNKAEwS0msMx08ENFgNXwbOFMMy0GAAdRhJGQAA4AAwvXUQFEGplMcG6uB07Jw5oARxMuGajOZrKQSPZpJRFEJxOD+J4cAAiiYcHBFS9RA0jTsTUg5UmmbgavQAMLpFng7BQBMvEwogAqGrBAepAF960A) as well, etc.

**Comment by JKillian** [comment]
Merged via #144 / #164 and released in 3.6.0!

@j13z if we decide we do want to add that option, it should fit consistently with the current rule name. (The rule controls the presence of the space before the closing of the tag, the name, to me, doesn't specifically need to mean that a space must be present)
