### ISSUE TITLE
Add in `no-unknown-property` rule

### ISSUE THREAD

**Issue by briangonzalez** [palantir/tslint-react#135]
If someone can point me in the right direction, I can take a stab it it.

https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/no-unknown-property.js

**Comment by cheeZery** [comment]
Shouldn't using TypeScript be enough from preventing you from using unknown element properties? :thinking:

**Comment by giladgray** [comment]
yes I agree that this should be handled by typescript itself.
