### ISSUE TITLE
New rule: jsx-tag-spacing

### ISSUE THREAD

**Issue by ajcrites** [palantir/tslint-react#143]
To mirror https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md

I have an attempt at this: https://github.com/ajcrites/tslint-react/blob/jsx-tag-spacing/src/rules/jsxTagSpacingRule.ts

... but I'm getting stuck trying to work through the ESLint version. Currently I've worked up to https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-tag-spacing.js#L98, but I'm not sure how to get the analogous token.

**Comment by adidahiya** [comment]
Closing due to deprecation timeline, see #210
