### ISSUE TITLE
New rule: jsx-curly-brace-presence

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [palantir/tslint-react#149]
In order to ensure a consistent jsx code style we need a rule to disallow/enforce unnecessary curly braces.

See [eslint-plugin-react - jsx-curly-brace-presence](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md#enforce-curly-braces-or-disallow-unnecessary-curly-braces-in-jsx-props-andor-children-reactjsx-curly-brace-presence) for reference

**Comment by FDiskas** [comment]
Any news? :smiling_imp:

**Comment by wh1t3cAt1k** [comment]
Also need this
