### ISSUE TITLE
New Rule: No used props

### ISSUE THREAD

**Issue by bluerface** [palantir/tslint-react#151]
Useful for dead code elimination

**Comment by johnwiseheart** [comment]
Hi there @bluerface,

Can you go into a little more detail as to how you would expect this rule to work, perhaps with some examples?

**Comment by no23reason** [comment]
I believe they meant *un*used props, something like
```tsx
const Foo = (props: {name: string; unusedProp: number}) => <div>Hi, {props.name}</div>
                                                          ~~~~~~~~~~~~~~~ The prop 'unusedProp' is not used anywhere in the component.
```

**Comment by karol-majewski** [comment]
The previous issue proposed the same thing: #150. There is a rule like this in `tslint-microsoft-contrib`, but [it doesn't work with stateless components](https://github.com/Microsoft/tslint-microsoft-contrib/issues/339).

**Comment by adidahiya** [comment]
This request doesn't look any different from `no-unused-variable`, which is [deprecated for maintenance reasons](https://github.com/palantir/tslint/issues/4100).
