### ISSUE TITLE
Require state initialization

### ISSUE THREAD

**Issue by jeremejevs** [palantir/tslint-react#152]
Right now, the following is possible:

```ts
class A extends Component<{}, { foo: string }> {
  render() {
    return <div>{this.state.foo}</div>; // Runtime error, `state` is null
  }
}
```

I haven't done a thorough research, but doesn't seem like there's a way to address this through typings. So maybe a rule could be added, requiring state initialization, at least when it's explicitly typed:

```ts
class A extends Component<{}, { foo: string }> {
  state = null // Compile-time error, can't be null

  render() {
    return <div>{this.state.foo}</div>;
  }
}
```

~~Or require the state type to be nullable:~~ This doesn't work with current typings:

```ts
class A extends Component<{}, { foo: string } | null> {
  render() {
    return <div>{this.state.foo}</div>; // Compile-time error, `state` may be null
  }
}
```

Thoughts?

**Comment by johnwiseheart** [comment]
I think this is a good idea - definitely see this issue pop up now and again and it would be good to check against it. The TSLint team doesn't have a lot of bandwidth to write new rules at the moment, but will accept pull requests for this.

**Comment by adidahiya** [comment]
Closing due to deprecation timeline, see #210
