### ISSUE TITLE
jsx-wrap-multiline false positive with generic type parameter definitions

### ISSUE THREAD

**Issue by wa4-fearless-otter** [palantir/tslint-react#158]
Throws this error on arrow functions if `jsx-wrap-multiline` is turned on. Happen obviously only in .tsx files.

![screenshot from 2018-04-22 21-45-34](https://user-images.githubusercontent.com/15262665/39099218-1a8f8952-4677-11e8-9802-9a89dc8be845.png)

**Comment by JKillian** [comment]
Hey @Wavum, thanks for the report! Can you post the text of a full file in which you see this error happen? Also, what version of tslint/typescript?

**Comment by andrew-buckley** [comment]
We have this bug occurring in our project as well. The line @wa4-fearless-otter has above should cause the bug to appear: `const test = <T>(a: number): void => a = 1;`

**Comment by adidahiya** [comment]
Closing due to deprecation, see #210
