### ISSUE TITLE
Prettier quotemark

### ISSUE THREAD

**Issue by Kronuz** [palantir/tslint-react#160]
Allow quotemark to use single quotes without clashing with Prettier rule about using double quotes on strings with `'` int it. Ex.: `"can't be used with single quotemark"`.

**Comment by JKillian** [comment]
I believe this is about the [TSLint `quotemark` rule](https://palantir.github.io/tslint/rules/quotemark/), not about tslint-react. That said, there's an [`"allow-escape"` option](https://palantir.github.io/tslint/rules/quotemark/) that should do what you need!
