### ISSUE TITLE
New rule: require explicitly typed `defaultProps`

### ISSUE THREAD

**Issue by andrewbranch** [palantir/tslint-react#169]
It's easy write a component with unsafe defaultProps:

```tsx
interface MyComponentProps {
  onClick?: React.MouseEventHandler<HTMLElement>;
}

class MyComponent extends React.Component<MyComponentProps> {
  static defaultProps = {
    onClick: 42
  };

  render() {
    return <div onClick={this.props.onClick} />;
  }
}
```

So it's useful to enforce declaring an explicit type for `static defaultProps` (which should basically always be `Partial<P>` where `P` is the type of the component’s props), which would catch such silly mistakes:

```tsx
interface MyComponentProps {
  onClick?: React.MouseEventHandler<HTMLElement>;
}

class MyComponent extends React.Component<MyComponentProps> {
  static defaultProps: Partial<MyComponentProps> = {
  //     ^^^^^^^^^^^^ Type { onClick: number } is not convertible to Partial<MyComponentProps> or some error message along these lines
    onClick: 42
  };
}
```

**Comment by suchanlee** [comment]
I think it would be useful and would be happy to accept a PR!

**Comment by andrewbranch** [comment]
I think to do this right, we’d need to use the type checker `ts.createProgram` to tell whether or not a class declaring `defaultProps` is in fact a React component. However, I'm not sure what the overhead for that is, and if it would be worth it just to check the AST for the text `React.Component` and maybe `Component`, also checking that `Component` is being imported from `'react'` at some point (presumably faster but not as accurate). What are your feelings on it?

**Comment by andrewbranch** [comment]
Actually, in TypeScript 3.0, you [don’t want to explicitly type defaultProps](https://blogs.msdn.microsoft.com/typescript/2018/07/12/announcing-typescript-3-0-rc/#default-props-support). So, maybe instead of requiring an explicit type, a rule that checks that the inferred type of `defaultProps` is assignable to the class’s props interface would be valuable—which would _definitely_ require the type checker.

**Comment by cheeZery** [comment]
Also see this discussion (which unfortunately currently seems to be on hold): https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28515

**Comment by adidahiya** [comment]
> a rule that checks that the inferred type of defaultProps is assignable to the class’s props interface

this sounds like a good idea, but it should now be an eslint rule. see #210
