### ISSUE TITLE
New rule suggestion: no-access-state-in-setstate

### ISSUE THREAD

**Issue by zerkms** [palantir/tslint-react#172]
This is the same as https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md

The purpose: to deny using `this.state` inside `this.setState` call.

Why: Given `this.setState` mutates the state asynchronously it's extremely easy to introduce a subtle bug when in 2 sequential calls one relies on a particular `this.state` state. And if those `this.setState` calls are in different functions and spatially not even close the problem might be really challenging to debug.

**Comment by cheeZery** [comment]
Oh my, I already submitted a PR (#190) for this issue but somehow linked the wrong issue back then.. so, here you go :)

**Comment by karfau** [comment]
Since #190 was reverted in #211 this issue has not been fixed.

**Comment by cheeZery** [comment]
In case your wondering about the progress of this issue: I started working on the typed rule but ran into some problems and now need a bit of help :-) Feel free to share your knowledge ♥
https://github.com/palantir/tslint-react/pull/190#issuecomment-478276892

**Comment by adidahiya** [comment]
This suggestion is still a good idea, but it should be migrated to an eslint rule. See #210

**Comment by karfau** [comment]
no need to migrate it, the idea came from an eslint rule, see [description](https://github.com/palantir/tslint-react/issues/172#issue-341422951)
