### ISSUE TITLE
New rule suggestion: jsx-sort-comp

### ISSUE THREAD

**Issue by tenorok** [palantir/tslint-react#183]
Analogue to [eslint-plugin-react/react/sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md).

**Comment by kacimimoghite** [comment]
Any news about this suggestion ??

**Comment by adidahiya** [comment]
Sounds like a good idea, but we are closing requests for new rules due to the deprecation timeline: #210
