### ISSUE TITLE
loop in js-wrap-multilines

### ISSUE THREAD

**Issue by liajoy** [palantir/tslint-react#185]
Hi! What do you think about using loop rendering in this form?
How to write loop under jsx-wrap-multilines rule?

    return (
        <ul>
            <li>
                {
                    [1, 2, 3].map(i => (
                        <span>
                            <b>i</b>
                        </span>
                    ))
                }
            </li>
        </ul>
    );

**Comment by adidahiya** [comment]
Not sure what your question is exactly. What is the lint output you get with that code? And what do you expect the lint output to be?
