### ISSUE TITLE
New rule suggestion: no-spaces-in-singleline

### ISSUE THREAD

**Issue by vjsingh** [palantir/tslint-react#188]
Currently, the following will cause a generic React Native error on Android, with no line number or file. This makes debugging difficult:

`<Tag> {children}</Tag>`
(see https://github.com/facebook/react-native/issues/18773)

It would be nice if tslint could catch these extra spaces in single-line JSX for me.

Alternatively, a more brutish approach could be to disallow single line JSX entirely, but that isn't a great solution.

*by single-line JSX I mean lines with the opening and closing tags on the same line

**Comment by adidahiya** [comment]
Seems to be addressed in ESLint according to that issue thread you linked. Also closing due to #210

**Comment by vjsingh** [comment]
Fair enough, thanks @adidahiya
