### ISSUE TITLE
React must be in scope in tsx file

### ISSUE THREAD

**Issue by JasonZough** [palantir/tslint-react#193]
I think this is a basical rule for tsx file.

**Comment by luhis** [comment]
I think this sounds like a good idea.  If it does not import React, it should just be a regular .ts file.  I will have a go a see what I can do.

**Comment by luhis** [comment]
i've had a go at this here:
https://github.com/luhis/tslint-react/commits/master

I think this might not quite feel right, as the rule linter doesn't know what is a React style file and what isn't.  We could add a setting for it, so a setting to say that .tsx and .jsx must import react, but that sounds a bit messy.   Does anyone have a better idea?

**Comment by adidahiya** [comment]
Can you flesh out this rule proposal a bit more? What kind of code passes for this rule? What kind of code fails? Is this just about the file extension?

**Comment by adidahiya** [comment]
Closing due to deprecation timeline, see #210
