### ISSUE TITLE
Rule suggestion: no unneeded <React.Fragment> or <>

### ISSUE THREAD

**Issue by dikujepsen** [palantir/tslint-react#198]
Sometimes I see programmers on my team using the React.Fragment or <> component around a single child, such as a div, in which case I think it might as well be deleted.
```typescript
<React.Fragment>
    <div>
        <Component1 />
        <Component2 />
        <Component3 />
    </div>
</React.Fragment>
```

Would it be possible to make a rule that enforces this?

**Comment by adidahiya** [comment]
I would call it `react-no-unnecessary-fragment`
