### ISSUE TITLE
Pull in rules from tslint-microsoft-contrib

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint-react#202]
[tslint-microsoft-contrib](https://github.com/Microsoft/tslint-microsoft-contrib) has several React-related rules, particularly around accessibility, that really belong in this repository:

* `react-a11y-accessible-headings`
* `react-a11y-iframes`
* `react-a11y-anchors`
* `react-a11y-aria-unsupported-elements`
* `react-a11y-event-has-role`
* `react-a11y-image-button-has-alt`
* `react-a11y-img-has-alt`
* `react-a11y-input-elements`
* `react-a11y-lang`
* `react-a11y-meta`
* `react-a11y-no-onchange`
* `react-a11y-props`
* `react-a11y-proptypes`
* `react-a11y-required`
* `react-a11y-role-has-required-aria-props`
* `react-a11y-role-supports-aria-props`
* `react-a11y-role`
* `react-a11y-tabindex-no-positive`
* `react-a11y-titles`
* `react-anchor-blank-noopener`
* `react-iframe-missing-sandbox`
* `react-no-dangerous-html`
* `react-this-binding-issue`
* `react-tsx-curly-spacing`
* `react-unused-props-and-state`

Would you accept PRs to move them here? Are there preferences around this?

**Comment by adidahiya** [comment]
Is there a downside to leaving them where they are now?

**Comment by JoshuaKGoldberg** [comment]
I believe it's been a point of confusion for users that there are two popular contributed rulesets with React-specific rules. Prior to the TSLint deprecation plans and this repository being somewhat unmaintained, it would have been nice to better delineate which rules go where.

At this point, I'm ok with taking no action.

**Comment by adidahiya** [comment]
Closing due to deprecation timeline, see #210
