### ISSUE TITLE
Cannot set "jsx-boolean-value" to 'never' ?

### ISSUE THREAD

**Issue by murbanowicz** [palantir/tslint-react#203]
Hi,

This is my `tslint.json`:
```
"extends": [
    "tslint:latest",
    "tslint-react",
    "tslint-config-airbnb",
    "tslint-config-prettier"
  ],
  "jsRules": {},
  "rules": {
    "jsx-boolean-value": "never",
```

`never` has no effect. I am forced to use value for boolean values when what I want to do is to have no value set.
What is the reason of that?

**Comment by benhamlin** [comment]
There appears to be a documentation bug, because setting the rule to false disables the rule.

**Comment by benhamlin** [comment]
"always" or "never" are rule _options_, so you need to use:
`"jsx-boolean-value": [true, "never"]`

**Comment by damianmr** [comment]
Woha! I had the same problem... Is it ok to clear this out in the docs? I can make a PR for that
