### ISSUE TITLE
Migrate to eslint-plugin-react

### ISSUE THREAD

**Issue by VincentLanglet** [palantir/tslint-react#208]
[Tslint is going to be deprecated in favor of eslint](https://github.com/palantir/tslint/issues/4534)
There is a [typescript parser](https://github.com/typescript-eslint/typescript-eslint) to use eslint for typescript files.

Are you considering to migrate rules and deprecate tslint-react in favor of eslint-plugin-react ?

**Comment by adidahiya** [comment]
Yes, but I don't have any more specific updates yet besides what I wrote in https://github.com/palantir/tslint/issues/4534

**Comment by adidahiya** [comment]
closing in favor of #210
