### ISSUE TITLE
react-ssr-friendly

### ISSUE THREAD

**Issue by cyberhck** [palantir/tslint-react#209]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**
This is a general purpose rule which actually should be enabled by default IMO (but that can be discussed later)

**What does your suggested rule do?**
It should check few methods in react projects, constructor, getDerivedStateFromProps, componentWillMount (deprecated), render (maybe more? We can list them later), and see if the code will be able to run in node env, it won't be perfect, but can we blacklist few things to be used there.

Example would include: document, window, localStorage (other types of browser storage etc)

**List several examples where your rule could be used**
I could enable this rule and later if project decides to use server side rendering, thanks to this rule, we'd have avoided those refactoring awkwardness.

**Additional context**
Not sure entirely, I've not written a lot of rules (just maybe around 3-4), let's discuss and see if we can proceed, if I get some time, I could also send a PR.

**Comment by adidahiya** [comment]
Sounds like a good idea, but I would suggest making this an ESLint ruleset instead. See #210
