### ISSUE TITLE
jsx-self-close rule doesn't actually support autofix

### ISSUE THREAD

**Issue by dmitriykozlov** [palantir/tslint-react#213]
### Bug Report

- __tslint-react version__: 3.6.0
- __tslint version__: 5.14.0
- __typescript version__: 3.3.4000
- __Running TSLint via__: Node.js API / Webstorm / CLI

#### TypeScript code being linted

```ts
ReactDOM.render(
    <App compiler={'Type'}></App>,
    document.getElementById('root')
)
```

with `tslint.json` configuration:

```json
{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended",
        "tslint-config-prettier",
        "tslint-react"
    ],
    "jsRules": {},
    "rules": {},
    "rulesDirectory": []
}
```

#### Actual behavior
Running linter with --fix flag detects an error 
```
 tslint ./src/**/* --fix

ERROR: src/index.tsx:7:5 - JSX elements with no children must be self-closing
```
but in the end file stays the same
#### Expected behavior
TSLint fixes code according to jsx-self-close rule

**Comment by adidahiya** [comment]
that was only released in 4.0.0: https://github.com/palantir/tslint-react/releases/tag/4.0.0

but it looks like the publish did not succeed in CI. I will re-publish
