### ISSUE TITLE
New Rule: jsx-quotes

### ISSUE THREAD

**Issue by avanderhoorn** [palantir/tslint-react#23]
Enforce the consistent use of either double or single quotes in JSX attributes (jsx-quotes).

This is basically a copy of http://eslint.org/docs/rules/jsx-quotes for tsx pages.

**Comment by avanderhoorn** [comment]
If it helps:
 - Source - https://github.com/eslint/eslint/blob/master/lib/rules/jsx-quotes.js
 - Tests - https://github.com/eslint/eslint/blob/master/tests/lib/rules/jsx-quotes.js

**Comment by rluiten** [comment]
Having just run through my code base with tslint it comes to mind I would like more control than just a preferred quote type. 

I'd love if I could specify one type of quote for code and a different type of quote for JSX attribute values, I do realise this may not be feasible. My JSX attributes use double quotes and the rest of my code base is single.

**Comment by JKillian** [comment]
Actually, these features are available though the core [`quotemark`](http://palantir.github.io/tslint/rules/quotemark/) rule already. This whole rule actually isn't needed since it's built into core. Hope this helps everyone!

**Comment by rluiten** [comment]
Excellent, thank you @JKillian.

**Comment by gugadev** [comment]
@JKillian Hmm, I think is a good idea to separate them. I use the rule `quotemark`  to plain Typescript code but I would like to have a `jsx-quotemark` rule for React. Reason? because the linter forces me to apply single quote for props (and it shouldn't be IMO).
