### ISSUE TITLE
New Rule: jsx-no-spread-attributes

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint-react#30]
unfortunately [JSX spread attributes](https://facebook.github.io/react/docs/jsx-spread.html) in typescript are not type checked very strictly 😞

**Comment by adidahiya** [comment]
This no longer applies in TypeScript 2.1. Spreads are now properly type checked!

**Comment by tristanisme** [comment]
> @adidahiya said...
> This no longer applies in TypeScript 2.1. Spreads are now properly type checked!

This is [no longer true](https://github.com/Microsoft/TypeScript/issues/16429) so perhaps this issue should be re-opened.

I'd like to target the specific type checking issue though. How difficult would it be to create a lint rule that forbids excess props in spread attributes? I attempted this. I could detect what's in a spread attribute, but I couldn't find a way to determine what *should* be in it.
