### ISSUE TITLE
No lambda in JSX and lamda ref conflict

### ISSUE THREAD

**Issue by isergey** [palantir/tslint-react#33]
If ref defined as lamda, tslint warn about no lambda in JSX. But ref is string attr, tslint warn about callback to ref prop. 

[tslint] Lambdas are forbidden in JSX attributes due to their rendering performance impact
```jsx
<input type="input" ref={(c) => this._input = c} />
```

[tslint] Pass a callback to ref prop instead of a string literal
```jsx
<input type="input" ref="input" />
```

**Comment by adidahiya** [comment]
This is intentional. The recommended pattern for satisfying the `jsx-no-lambda` rule is to bind your callback elsewhere, not inline. This is orthogonal to the `jsx-no-string-ref` rule.

**Comment by adidahiya** [comment]
Also see #26

**Comment by JKillian** [comment]
Closing as there's no action to take here
