### ISSUE TITLE
jsx-wrap-multiline is a breaking change

### ISSUE THREAD

**Issue by lukevenn** [palantir/tslint-react#51]
Hi,

Just wondered if you're using semantic versioning? We are extending tslint-react using version 2.*. The new `jsx-wrap-multiline` rule in 2.1 is causing our builds to fail without us making any changes to the default value which I believe should make it a breaking change. Am I wrong?

Thanks,
Luke

**Comment by adidahiya** [comment]
Hey, sorry about that -- so far I've been treating `tslint-react.json` like `tslint:latest`, which does not follow semver. I suppose it'd be nice to introduce the same semantics as the core configurations, where you have the option of a stable or a bleeding edge configuration, I just haven't gotten around to supporting that. Would likely take a PR for it though.

**Comment by adidahiya** [comment]
closing in favor of #76
