### ISSUE TITLE
New rule: Wrap expressions in a line 

### ISSUE THREAD

**Issue by mohsen1** [palantir/tslint-react#66]
Not sure how to name or describe this rule. 

**Bad**
```ts
<div>{
  expression
}</div>
```

**Good**
```ts
<div>
  {expression}
</div>
```

**Comment by adidahiya** [comment]
maybe this could be a new option in `jsx-curly-spacing`? or a new rule called `jsx-one-line`

**Comment by adidahiya** [comment]
Closing due to old age and the deprecation timeline in #210
