### ISSUE TITLE
New Rule: jsx-alignment

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint-react#7]
Enforce this alignment when tags span multiple lines:

```ts
<input
    type="search"
    placeholder="Search..."
/>
```

**Comment by JKillian** [comment]
I'll implement this one!

**Comment by JKillian** [comment]
Maybe it should be called `jsx-multiline-format`?

**Comment by adidahiya** [comment]
I like "align" because it matches up somewhat with the core `align` rule. I think "align" also implies multiline.
