### ISSUE TITLE
New rule: disallow fat-arrow when declaring lifecycle functions

### ISSUE THREAD

**Issue by cmslewis** [palantir/tslint-react#74]
See this recent bug in Blueprint: https://github.com/palantir/blueprint/issues/801

Using a fat arrow for `componentDidMount` broke global hotkeys for the component in question. Would be great to disallow that for each of the React lifecycle functions.

Note; This might be catchable with the tslint `no-unbound-method` rule.

**Comment by adidahiya** [comment]
name suggestion: `react-lifecycle-method-context`

**Comment by alexwalter88** [comment]
This is actually fixed by more recent versions of `@types/react`. When you try to do this, it shows the error message:
> Class 'Component<MyProps, {}>' defines instance member function 'componentDidMount', but extended class 'MyComponent' defines it as an instance member property.

**Comment by adidahiya** [comment]
@alexwalter88 neat! thanks for the heads up. I think it's safe to close this out in favor of the compiler check.
