### ISSUE TITLE
Development > Quick steps might use global TSLint during rules verification

### ISSUE THREAD

**Issue by IllusionMH** [palantir/tslint-react#82]
`scripts/verify.sh` uses `tslint` executable from `PATH` and if launched not from `npm`/`yarn` script (as shown in Quick steps) will use global TSLint installation.

Possible solutions:

1. Use `tslint` executable from `node_modules` in `verify.sh` file
`./node_modules/.bin/tslint -r ./build/rules/ --test $path/..`

1. Add local installation to path in Quick steps
`PATH=./node_modules/.bin:$PATH ./scripts/verify.sh`

**Comment by adidahiya** [comment]
Good catch. I prefer option (1)
