### ISSUE TITLE
add empty "index.js" to "rules/" directory

### ISSUE THREAD

**Issue by donaldpipowitch** [palantir/tslint-react#92]
Given https://github.com/palantir/tslint/issues/2163 it would be nice, if the `rules/` directory would contain an empty `index.js`. Then we could resolve the rules directory with Nodes module resolution which makes it easy to use custom rules in certain situations (symlinked configs, flat vs. non-flat installations...).

Motivation:
- `extends`: Allows me to use custom rules from other packages. I get all rules with default configs and can _opt-out_ from rules. If new rules are added in new version I get them automatically.
- `rulesDirectory `: Allows me to use custom rules from other packages. I _opt-in_ to use certain rules with my specific configs. If new rules are added in new version I don't get them automatically.

**Comment by adidahiya** [comment]
open to PRs
