### ISSUE TITLE
jsx-use-translation-function option to specify which prop/attribute to check

### ISSUE THREAD

**Issue by MastroLindus** [palantir/tslint-react#98]
the jsx-use-translation-function is very useful already, but it cannot identify problems when strings that need to be translated are passed in as certain props.
For example, if a component accepts a prop "label", we might want to be sure that is not a string literal.

The rule contains some hardcoded names (e.g. "title") that do get checked, but there's no way to specify extra ones in case a component uses one that is not part of that hardcoded list.

It would be very useful if the rule would accept an option to specify a list of prop/attribute names to check.

**Comment by adidahiya** [comment]
Makes sense. There are core TSLint rules with similar configuration options. I'd accept a PR for this enhancement.

**Comment by Kolombiken** [comment]
Seems very useful! 
I would very much also like to have an option of passing in empty strings as alt-attributes. If I can set a rule that says that empty string literal is totally ok for alt-attributes that would be great.

(In case someone is not sure about why I would want to do that this is why: https://www.w3.org/WAI/tutorials/images/decorative/)

**Comment by adidahiya** [comment]
Closing due to deprecation, see #210
